const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d');
let selected=new Set([0,1,2,3,4,5]),battle=null,running=false,replaySeed=false,seed=1337,round=1,follow=null,sound=false,audio=null,last=0,uiTime=0,seen=0;
function sprite(c,x,y,f,scale=3,walk=0){c.save();c.translate(Math.round(x),Math.round(y));c.scale(scale,scale);const rect=(a,b,w,h,color)=>{c.fillStyle=color;c.fillRect(a,b,w,h);};let shift=Math.sin(walk*9)>0?1:0;rect(-6,0,5,5+shift,'#141822');rect(1,0,5,6-shift,'#141822');rect(-6,-13,12,14,f.color);rect(-9,-12,3,9,'#e7b59c');rect(6,-12,3,9,'#e7b59c');rect(-5,-24,10,11,'#e7b59c');rect(-6,-26,12,5,'#292535');rect(-5,-25,3,7,'#292535');rect(-2,-20,2,2,'#151923');rect(3,-20,2,2,'#151923');rect(-1,-15,4,1,'#986d69');rect(-3,-10,6,3,'#ffffff33');switch(f.hat){case 0:rect(-6,-29,12,3,f.color);rect(-3,-33,2,4,f.color);rect(2,-33,2,4,f.color);break;case 1:rect(-7,-28,14,3,f.color);rect(-4,-33,8,5,f.color);rect(-2,-37,4,4,f.color);break;case 2:rect(-7,-24,14,2,f.color);rect(7,-23,4,3,f.color);break;case 3:rect(-5,-20,4,3,'#fff');rect(1,-20,4,3,'#fff');rect(-1,-19,2,1,'#fff');break;case 4:case 8:rect(-6,-29,12,4,f.color);rect(-6,-33,3,4,f.color);rect(-1,-34,3,5,f.color);rect(4,-33,3,4,f.color);break;case 5:rect(-9,-21,3,4,f.color);rect(6,-21,3,4,f.color);break;case 6:rect(-6,-27,12,7,f.color);rect(-5,-18,10,4,'#302742');break;case 7:rect(-7,-28,14,12,'#8690a1');rect(-5,-21,10,3,'#172028');break;case 9:rect(-6,-28,12,5,'#fff');rect(-1,-27,2,4,f.color);rect(-2,-26,4,2,f.color);break;case 10:rect(-7,-28,14,3,f.color);rect(-4,-31,8,3,'#37304a');break;case 11:rect(-6,-28,12,5,f.color);rect(-4,-33,3,5,f.color);rect(2,-31,3,3,f.color);break;}c.restore();}
function renderRoster(){ $('selectedCount').textContent=selected.size+' / 12';$('roster').innerHTML='';Brawl.roster.forEach((f,i)=>{const b=document.createElement('button');b.className='fighter-card'+(selected.has(i)?' selected':'');b.style.setProperty('--accent',f.color);b.setAttribute('aria-pressed',selected.has(i));b.setAttribute('aria-label',f.name+', '+f.skill+'. '+f.desc);b.disabled=!!battle&&!battle.done;b.innerHTML='<div class="card-top"><canvas class="portrait" width="52" height="55"></canvas><span class="check">'+(selected.has(i)?'✓':'')+'</span></div><span class="role">'+f.role+'</span><h3>'+f.name+'</h3><div class="skill-name">'+f.skill+'</div><span class="skill-desc">'+f.desc+'</span><div class="card-stats"><span>'+f.hp+' HP</span><span>'+f.cd+'s SKILL</span></div>';b.onclick=()=>{if(selected.has(i)){if(selected.size<=2){$('state').textContent='MINIMUM 2';return;}selected.delete(i);}else selected.add(i);battle=null;running=false;seen=0;renderRoster();updateUI();};$('roster').appendChild(b);sprite(b.querySelector('canvas').getContext('2d'),26,42,f,1.4);});$('all').disabled=$('random').disabled=!!battle&&!battle.done;}
function start(){if(battle&&!battle.done){running=true;return;}if(!replaySeed)seed++;replaySeed=false;battle=new Brawl.Battle([...selected],seed);running=true;follow=null;seen=0;$('feed').innerHTML='';battle.log('The gates open. '+selected.size+' fighters enter.','#befb58');renderRoster();updateUI();}
function reset(){replaySeed=!!battle||replaySeed;battle=null;running=false;follow=null;seen=0;$('feed').innerHTML='<p class="muted">Roster unlocked. Pick your fighters, then start the brawl.</p>';$('overlay').hidden=false;$('overlay').querySelector('.eyebrow').textContent='THE ROSTER IS READY';$('overlay').querySelector('h2').textContent='Ready for a rematch?';$('overlay').querySelector('p').textContent='Change your roster or start again. Reset keeps the previous battle seed.';$('overlayStart').textContent='START THE BRAWL';renderRoster();updateUI();}
function beep(){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.setValueAtTime(220+Math.random()*220,audio.currentTime);g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.07);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.08);}catch{sound=false;}}
function time(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');}
function updateUI(){const fighters=battle?battle.fighters:[...selected].map(id=>({...Brawl.roster[id],id,health:Brawl.roster[id].hp,kills:0,damage:0,skillLeft:0}));$('alive').textContent=fighters.filter(f=>f.health>0).length;$('clock').textContent=time(battle?.time||0);$('round').textContent=round;$('state').textContent=battle?.done?'FINISHED':running?'LIVE':battle?'PAUSED':'READY';$('sudden').textContent=battle?.time>45?'SUDDEN DEATH · DAMAGE RISING':'EVERY FIGHTER FOR THEMSELVES';$('pause').disabled=!battle||battle.done;$('pause').textContent=running?'PAUSE':'RESUME';$('start').textContent=battle?.done?'NEW BRAWL':battle?'CONTINUE':'START THE BRAWL';if(running)$('overlay').hidden=true;$('standings').innerHTML='';fighters.sort((a,b)=>(b.health>0)-(a.health>0)||b.kills-a.kills||b.health-a.health).forEach((f,i)=>{const b=document.createElement('button');b.className='standing'+(f.health<=0?' dead':'')+(f.id===follow?' follow':'');b.innerHTML='<span style="color:'+f.color+'">'+(i+1)+'</span><div><strong>'+f.name+'</strong><div class="hp-track"><div class="hp-fill" style="width:'+Math.max(0,f.health/f.hp*100)+'%;background:'+f.color+'"></div></div></div><small>'+Math.ceil(f.health)+' HP<br>'+f.kills+' KO</small>';b.onclick=()=>{follow=follow===f.id?null:f.id;updateUI();};$('standings').appendChild(b);});if(battle){const events=battle.events.slice(seen);for(const e of events){const p=document.createElement('p');p.innerHTML='<span class="time">'+time(e.time)+'</span><span></span>';p.lastElementChild.textContent=e.text;p.lastElementChild.style.color=e.color;$('feed').prepend(p);beep();}seen=battle.events.length;while($('feed').children.length>30)$('feed').lastChild.remove();}if(battle?.done){running=false;$('overlay').hidden=false;const winner=battle.winner;$('overlay').querySelector('.eyebrow').textContent='BRAWL COMPLETE';$('overlay').querySelector('h2').textContent=winner?winner.name+' takes the crown.':'Double knockout.';$('overlay').querySelector('p').textContent=winner?winner.kills+' knockouts · '+Math.round(winner.damage)+' damage · '+time(battle.time)+' survived.':'Nobody gets bragging rights this time.';$('overlayStart').textContent='NEXT BRAWL';renderRoster();}}
const reducedMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function effect(e){const t=1-e.life/e.max,r=e.radius||85;ctx.save();ctx.globalAlpha=Math.min(1,e.life/e.max*2);ctx.fillStyle=e.color;ctx.strokeStyle=e.color;ctx.lineWidth=3;ctx.translate(e.x,e.y);const line=(x,y,tx,ty)=>{ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(tx,ty);ctx.stroke();};const circle=(radius)=>{ctx.beginPath();ctx.arc(0,0,radius,0,Math.PI*2);ctx.stroke();};const blade=(angle,len=55)=>{ctx.save();ctx.rotate(angle);ctx.fillStyle='#fff';ctx.fillRect(0,-3,len,6);ctx.fillStyle=e.color;ctx.fillRect(3,3,len-4,3);ctx.fillRect(2,-12,5,24);ctx.fillRect(-15,-4,16,8);ctx.restore();};
switch(e.type){
case'text':ctx.font='bold 14px monospace';ctx.textAlign='center';ctx.strokeStyle='#101821';ctx.lineWidth=3;ctx.strokeText(e.text,0,-t*32);ctx.fillText(e.text,0,-t*32);break;
case'particle':ctx.fillRect(e.vx*t,e.vy*t-20,4,4);break;
case'warning':ctx.globalAlpha=.12;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.85;ctx.setLineDash([9,7]);circle(r);ctx.setLineDash([]);circle(r*(1-t));ctx.font='bold 16px monospace';ctx.textAlign='center';ctx.fillText(e.text,0,5);break;
case'dash':{ctx.lineWidth=10;ctx.globalAlpha=.35;line(0,0,e.tx-e.x,e.ty-e.y);for(let i=0;i<5;i++){ctx.globalAlpha=(1-i/6)*(1-t)*.55;ctx.fillRect((e.tx-e.x)*i/5-10,(e.ty-e.y)*i/5-42,20,45);}break;}
case'sword':ctx.translate(0,-20);ctx.rotate((e.angle||0)+t*2.8);ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,38,-1,1.2);ctx.stroke();blade(0,54);break;
case'ice':for(let i=0;i<9;i++){const a=i/9*Math.PI*2,x=Math.cos(a)*r*.65,y=Math.sin(a)*r*.45,h=38+Math.sin(i*2)*15;ctx.beginPath();ctx.moveTo(x-10,y);ctx.lineTo(x,y-h*(Math.min(1,t*5)));ctx.lineTo(x+10,y);ctx.closePath();ctx.fill();ctx.fillStyle='#e4faff';ctx.fillRect(x-2,y-h*.6,3,h*.4);ctx.fillStyle=e.color;}circle(r*t);break;
case'icebeam':case'lightning':case'vine':case'flame':case'fork':case'feather':{const dx=e.tx-e.x,dy=e.ty-e.y;if(e.type==='lightning'){ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,0);for(let i=1;i<=7;i++)ctx.lineTo(dx*i/7+(i%2?10:-10),dy*i/7);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.stroke();}else if(e.type==='vine'){ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(dx*.3-35,dy*.3,dx*.7+35,dy*.7,dx,dy);ctx.stroke();for(let i=1;i<6;i++)ctx.fillRect(dx*i/6,dy*i/6,10,5);}else if(e.type==='icebeam'||e.type==='flame'){ctx.lineWidth=e.type==='flame'?9:4;line(0,0,dx,dy);for(let i=1;i<7;i++){ctx.save();ctx.translate(dx*i/7,dy*i/7);ctx.rotate(i+t*5);ctx.fillRect(-3,-10,6,20);ctx.restore();}}else{ctx.translate(dx*Math.min(1,t*3),dy*Math.min(1,t*3));ctx.rotate(Math.atan2(dy,dx));if(e.type==='fork'){ctx.fillRect(-13,-2,30,4);ctx.fillRect(12,-10,4,20);for(let i=-1;i<=1;i++)ctx.fillRect(14,i*8-1,11,3);}else{ctx.beginPath();ctx.moveTo(-20,0);ctx.lineTo(4,-9);ctx.lineTo(18,0);ctx.lineTo(4,9);ctx.closePath();ctx.fill();}}break;}
case'portal':ctx.scale(1,.5);ctx.lineWidth=7;circle(20+12*Math.sin(t*Math.PI));ctx.rotate(t*4);ctx.strokeStyle='#fff';ctx.setLineDash([4,8]);circle(30);break;
case'keyboard':ctx.translate(0,-(1-t)*110);ctx.rotate(-.12);ctx.fillStyle='#111824';ctx.fillRect(-65,-18,130,45);ctx.strokeRect(-65,-18,130,45);ctx.fillStyle=e.color;for(let y=0;y<3;y++)for(let x=0;x<10;x++)ctx.fillRect(-58+x*12,-12+y*12,9,8);break;
case'crack':ctx.lineWidth=4;for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.save();ctx.rotate(a);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(r*.3*t,8);ctx.lineTo(r*.6*t,-8);ctx.lineTo(r*t,4);ctx.stroke();ctx.restore();}circle(r*t);break;
case'anvil':ctx.translate(0,-180*(1-t));ctx.fillStyle='#c9d4e1';ctx.fillRect(-24,-30,48,10);ctx.fillRect(-14,-20,28,20);ctx.fillRect(-22,0,44,8);ctx.fillStyle=e.color;ctx.fillRect(-8,-18,16,10);break;
case'heal':circle(28+t*35);for(let i=0;i<5;i++){ctx.save();ctx.rotate(i*Math.PI*2/5);ctx.translate(40,-t*30);ctx.fillRect(-7,-2,14,4);ctx.fillRect(-2,-7,4,14);ctx.restore();}break;
case'shieldburst':circle(r*t);for(let i=0;i<5;i++){ctx.save();ctx.rotate(i*Math.PI*2/5+t*2);ctx.translate(r*t,0);ctx.fillRect(-9,-13,18,23);ctx.fillStyle='#fff';ctx.fillRect(-3,-8,6,15);ctx.restore();}break;
case'swordspin':for(let i=0;i<3;i++){ctx.save();ctx.rotate(t*14+i*Math.PI*2/3);ctx.translate(20,0);blade(0,42);ctx.restore();}circle(65);break;
case'eruption':for(let i=0;i<7;i++){ctx.save();ctx.translate((i-3)*18,0);ctx.fillStyle=i%2?'#fff08a':e.color;const h=(25+Math.sin(i*5)*15)*(1-t)*3;ctx.fillRect(-5,-h,10,h);ctx.restore();}circle(70*t);break;
case'ko':ctx.font='900 25px monospace';ctx.textAlign='center';ctx.fillText('KO',0,-35-t*35);circle(15+60*t);break;
default:circle(10+90*t);}
ctx.restore();}

function draw(){ctx.save();if(battle?.shake>0&&!reducedMotion)ctx.translate(Math.sin(battle.time*110)*battle.shake*15,Math.cos(battle.time*97)*battle.shake*10);ctx.clearRect(0,0,1000,580);ctx.fillStyle='#18242b';ctx.fillRect(0,0,1000,580);for(let y=0;y<580;y+=32)for(let x=0;x<1000;x+=32){ctx.fillStyle=(x/32+y/32)%2?'#1c2a31':'#1a272e';ctx.fillRect(x,y,31,31);}ctx.fillStyle='#111c24';ctx.fillRect(20,25,960,530);ctx.fillStyle='#22343a';ctx.fillRect(35,40,930,500);for(let y=48;y<530;y+=24)for(let x=43;x<950;x+=24){ctx.fillStyle=(x+y)%3?'#28383d':'#243439';ctx.fillRect(x,y,22,22);}ctx.strokeStyle='#71864a';ctx.lineWidth=3;ctx.strokeRect(36,41,928,498);ctx.strokeStyle='#364848';ctx.lineWidth=2;ctx.strokeRect(62,67,876,446);ctx.save();ctx.globalAlpha=.12;ctx.font='900 64px monospace';ctx.fillStyle='#befb58';ctx.textAlign='center';ctx.fillText('LUCASVERSE',500,285);ctx.font='900 28px monospace';ctx.fillText('THE PIXEL PIT',500,325);ctx.restore();const fighters=battle?battle.fighters:[...selected].map((id,i)=>{const a=i/selected.size*Math.PI*2;return {...Brawl.roster[id],id,x:500+Math.cos(a)*260,y:290+Math.sin(a)*175,health:Brawl.roster[id].hp,skillLeft:0};});
if(battle)for(const z of battle.zones){ctx.globalAlpha=.22;ctx.fillStyle=z.color;ctx.beginPath();ctx.arc(z.x,z.y,z.radius,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=z.color;ctx.setLineDash([6,8]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=z.color;if(z.kind==='trap'){ctx.fillRect(z.x-3,z.y-8,6,26);ctx.fillRect(z.x-13,z.y-10,26,5);for(let i=-1;i<=1;i++)ctx.fillRect(z.x+i*10-2,z.y-22,4,16);}else{for(let i=0;i<10;i++){const a=i*Math.PI/5;ctx.fillRect(z.x+Math.cos(a)*50-4,z.y+Math.sin(a)*40-15-Math.sin((battle?.time||0)*8+i)*8,8,25);}ctx.strokeStyle='#ffed91';ctx.beginPath();ctx.moveTo(z.x-45,z.y);ctx.lineTo(z.x-12,z.y-10);ctx.lineTo(z.x+12,z.y+8);ctx.lineTo(z.x+45,z.y-5);ctx.stroke();}}
for(const f of [...fighters].sort((a,b)=>a.y-b.y)){if(f.health<=0){ctx.globalAlpha=.35;ctx.fillStyle=f.color;ctx.fillRect(f.x-13,f.y-4,26,8);ctx.globalAlpha=1;continue;}ctx.save();if(f.evade>0)ctx.globalAlpha=.4;ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(f.x,f.y+13,24,8,0,0,Math.PI*2);ctx.fill();if(f.id===follow){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(f.x-32,f.y-89,64,110);}ctx.save();if(f.pose>0){ctx.translate(f.x,f.y);ctx.rotate(f.face*Math.sin(f.pose*15)*.12);ctx.translate(-f.x,-f.y);}if(f.flash>0)ctx.globalAlpha=.65;sprite(ctx,f.x,f.y,f,2,battle?.time||0);ctx.restore();if(f.orbit>0){for(let i=0;i<3;i++){const angle=(battle?.time||0)*5+i*Math.PI*2/3;ctx.fillStyle=f.color;ctx.fillRect(f.x+Math.cos(angle)*42-7,f.y-20+Math.sin(angle)*28-9,14,18);}}if(f.shield>0||f.reflect>0){ctx.strokeStyle=f.reflect>0?'#ff8faf':'#83d8ff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y-20,35,0,Math.PI*2);ctx.stroke();}ctx.textAlign='center';ctx.font='bold 14px monospace';ctx.fillStyle='#101821';ctx.fillRect(f.x-61,f.y-88,122,21);ctx.fillStyle=f.color;ctx.fillText(f.name,f.x,f.y-73);ctx.fillStyle='#111';ctx.fillRect(f.x-30,f.y-65,60,6);ctx.fillStyle=f.color;ctx.fillRect(f.x-30,f.y-65,60*f.health/f.hp,6);ctx.fillStyle='#83d8ff';ctx.fillRect(f.x-30,f.y-56,60*(1-Math.max(0,f.skillLeft)/f.cd),3);if(f.stun>0){ctx.fillStyle='#83d8ff';ctx.fillText('STUN',f.x,f.y+32);}ctx.restore();}
if(battle)for(const e of battle.effects)effect(e);ctx.restore();
}
function frame(t){const dt=Math.min((t-last)/1000,.08)||0;last=t;if(running&&battle){const steps=Math.ceil(dt*Number($('speed').value)/.025);for(let i=0;i<steps;i++)battle.step(dt*Number($('speed').value)/steps);}draw();uiTime+=dt;if(uiTime>.18){uiTime=0;updateUI();}requestAnimationFrame(frame);}
$('start').onclick=$('overlayStart').onclick=()=>{if(battle?.done){round++;battle=null;}start();};$('pause').onclick=()=>{running=!running;updateUI();};$('reset').onclick=reset;$('all').onclick=()=>{selected=new Set(Brawl.roster.map((_,i)=>i));battle=null;renderRoster();updateUI();};$('random').onclick=()=>{selected=new Set(Brawl.roster.map((_,i)=>i).sort(()=>Math.random()-.5).slice(0,6));battle=null;renderRoster();updateUI();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'SOUND ON':'SOUND OFF';$('sound').setAttribute('aria-pressed',sound);if(sound)beep();};$('rulesToggle').onclick=()=>{$('rules').hidden=!$('rules').hidden;$('rulesToggle').setAttribute('aria-expanded',!$('rules').hidden);};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['BUTTON','SELECT','INPUT'].includes(document.activeElement.tagName)){e.preventDefault();if(!battle||battle.done)$('start').click();else $('pause').click();}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'configure_brawl_roster',description:'Choose 2–12 fighters between battles using roster names.',inputSchema:{type:'object',properties:{names:{type:'array',items:{type:'string'},minItems:2,maxItems:12}},required:['names'],additionalProperties:false},execute:input=>{if(battle&&!battle.done)throw Error('Finish the current battle first.');if(!Array.isArray(input.names))throw Error('Provide fighter names.');const ids=input.names.map(n=>Brawl.roster.findIndex(f=>f.name===n));if(ids.length<2||ids.length>12||ids.some(i=>i<0)||new Set(ids).size!==ids.length)throw Error('Choose 2–12 different roster names.');selected=new Set(ids);battle=null;renderRoster();updateUI();return {fighters:input.names};}});document.modelContext.registerTool({name:'start_brawl',description:'Start or resume the visibly selected automatic battle.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{$('start').click();return {status:'running',fighters:[...selected].map(i=>Brawl.roster[i].name)};}});}catch{}}
renderRoster();updateUI();requestAnimationFrame(frame);
