(function(root){
const roster=[
{name:'Lucas',role:'CHAOS DUELIST',color:'#befb58',hp:180,atk:16,speed:76,range:46,cd:6,skill:'Forkidy Fork',desc:'Dash with afterimages; two crossing sword strikes.',kind:'dash',hat:0},
{name:'Cynthia',role:'FROST MAGE',color:'#83d8ff',hp:145,atk:13,speed:58,range:145,cd:7,skill:'Freeze Frame',desc:'A marked area erupts into ice spikes and freezes rivals.',kind:'frost',hat:1},
{name:'Junyi',role:'QUICK STRIKER',color:'#ffcc72',hp:155,atk:12,speed:100,range:44,cd:5,skill:'Triple Trouble',desc:'Blink around a rival in a three-slash combo.',kind:'triple',hat:2},
{name:'Mr. Eppley',role:'ARENA PROFESSOR',color:'#b5a1ff',hp:175,atk:14,speed:55,range:130,cd:8,skill:'Pop Quiz',desc:'Mark rivals with questions, then call down lightning.',kind:'quiz',hat:3},
{name:'Bro Council',role:'SHIELD CAPTAIN',color:'#ff9b84',hp:225,atk:11,speed:48,range:48,cd:8,skill:'Motion Approved',desc:'Spinning shields burst outward and knock rivals back.',kind:'shield',hat:4},
{name:'Fork Goblin',role:'TRAP MAKER',color:'#9effbb',hp:155,atk:12,speed:75,range:105,cd:6,skill:'Fork Mine',desc:'Leave an explosive fork trap behind.',kind:'trap',hat:5},
{name:'Pixel Phantom',role:'ELUSIVE ASSASSIN',color:'#ee9fff',hp:135,atk:17,speed:91,range:45,cd:7,skill:'Ghost Step',desc:'Teleport behind a rival; briefly evade hits.',kind:'ghost',hat:6},
{name:'Keyboard Knight',role:'HEAVY BRUISER',color:'#ffc36e',hp:240,atk:19,speed:42,range:55,cd:9,skill:'CAPS LOCK',desc:'Wide keyboard slam launches nearby rivals.',kind:'slam',hat:7},
{name:'Pigeon King',role:'SKY BOMBER',color:'#a8c8ff',hp:145,atk:12,speed:65,range:170,cd:7,skill:'Air Mail',desc:'Mark three spots for falling delivery anvils.',kind:'bomb',hat:8},
{name:'Doctor Cokking',role:'SELF HEALER',color:'#7cf3df',hp:170,atk:11,speed:62,range:110,cd:8,skill:'Suspicious Soup',desc:'A healing rune restores HP; vines poison a rival.',kind:'heal',hat:9},
{name:'Sock Samurai',role:'COUNTER FIGHTER',color:'#ff8faf',hp:185,atk:15,speed:72,range:48,cd:7,skill:'Laundry Revenge',desc:'Spin your blade, push rivals away and reflect hits.',kind:'reflect',hat:10},
{name:'Solar Gremlin',role:'FIRE CASTER',color:'#ffb85c',hp:150,atk:14,speed:62,range:150,cd:8,skill:'Pocket Sun',desc:'A warning circle erupts into a burning sun fissure.',kind:'fire',hat:11}
];
function random(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t^=t+Math.imul(t^t>>>7,61|t);return ((t^t>>>14)>>>0)/4294967296;};}
class Battle{
constructor(ids,seed=1337){if(ids.length<2||new Set(ids).size!==ids.length||ids.some(i=>!roster[i]))throw Error('Choose at least two distinct fighters.');this.rng=random(seed);this.time=0;this.done=false;this.winner=null;this.events=[];this.effects=[];this.projectiles=[];this.zones=[];this.pending=[];this.shake=0;this.fighters=ids.map((id,i)=>{const a=i/ids.length*Math.PI*2;return {...roster[id],id,x:500+Math.cos(a)*260,y:290+Math.sin(a)*175,health:roster[id].hp,shield:0,skillLeft:1.6+this.rng()*2,attackLeft:this.rng(),stun:0,evade:0,reflect:0,poison:0,kills:0,damage:0,face:1,lastHit:null};});}
log(text,color){this.events.push({time:this.time,text,color});}
fx(type,x,y,color,text,extra={}){const life=extra.life||(type==='text'?.85:.65);this.effects.push({type,x,y,color,text,life,max:life,...extra});}
schedule(a,delay,action){this.pending.push({owner:a.id,left:delay,action});}
burst(x,y,color,n=14){for(let i=0;i<n;i++){let angle=i/n*Math.PI*2;this.fx('particle',x,y,color,'',{vx:Math.cos(angle)*(45+this.rng()*85),vy:Math.sin(angle)*(45+this.rng()*85),life:.45+this.rng()*.35});}}
line(a,b,type,color){this.fx(type,a.x,a.y-18,color,'',{tx:b.x,ty:b.y-18});}
knock(a,b,power){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;b.x=Math.max(40,Math.min(960,b.x+dx/d*power));b.y=Math.max(65,Math.min(535,b.y+dy/d*power));}
attack(a,b){a.pose=.25;switch(a.kind){case'frost':this.line(a,b,'icebeam',a.color);break;case'quiz':this.line(a,b,'lightning',a.color);break;case'heal':this.line(a,b,'vine',a.color);break;case'fire':this.line(a,b,'flame',a.color);break;case'trap':this.line(a,b,'fork',a.color);break;case'bomb':this.line(a,b,'feather',a.color);break;default:this.fx('sword',b.x,b.y,a.color,'',{angle:Math.atan2(b.y-a.y,b.x-a.x)});}this.hit(a,b,a.atk);}

hit(a,b,amount,reflected=false){if(b.health<=0||b.evade>0)return;let damage=Math.max(1,Math.round(amount*(this.time>45?1+(this.time-45)/15:1)));if(b.reflect>0&&!reflected){this.hit(b,a,damage*.65,true);damage=Math.round(damage*.35);}let absorbed=Math.min(b.shield,damage);b.shield-=absorbed;damage-=absorbed;b.health=Math.max(0,b.health-damage);a.damage+=damage;b.lastHit=a.id;b.flash=.12;if(damage)this.burst(b.x,b.y-18,b.color,5);this.fx('text',b.x,b.y-40,damage?'#fff':'#95caff',damage?'-'+damage:'BLOCK');if(b.health===0){a.kills++;this.log(a.name+' knocked out '+b.name,'#ff968e');this.fx('ko',b.x,b.y,b.color,'',{life:1});this.burst(b.x,b.y,b.color,24);this.shake=.2;}}
shoot(a,b,amount,color,speed=320){this.projectiles.push({x:a.x,y:a.y-16,target:b.id,owner:a.id,amount,color,speed,life:3});}
skill(a,b){this.log(a.name+' · '+a.skill,a.color);this.fx('text',a.x,a.y-92,a.color,a.skill);a.pose=.7;const near=(x,y,r)=>this.fighters.filter(f=>f!==a&&f.health>0&&Math.hypot(f.x-x,f.y-y)<r);switch(a.kind){
case'dash':{const old={x:a.x,y:a.y};let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;a.x=b.x-dx/d*34;a.y=b.y-dy/d*34;this.fx('dash',old.x,old.y,a.color,'',{tx:a.x,ty:a.y,life:.5});this.hit(a,b,22);this.fx('sword',b.x,b.y,a.color,'',{angle:-.7});this.schedule(a,.18,()=>{this.hit(a,b,22);this.fx('sword',b.x,b.y,a.color,'',{angle:.7});this.knock(a,b,35);});break;}
case'frost':{const x=b.x,y=b.y;this.fx('warning',x,y,a.color,'ICE',{radius:115,life:.55});this.schedule(a,.55,()=>{this.fx('ice',x,y,a.color,'',{radius:115,life:1.3});for(const f of near(x,y,115)){f.stun=1.4;this.hit(a,f,38);}});break;}
case'triple':for(let i=0;i<3;i++)this.schedule(a,i*.2,()=>{if(b.health<=0)return;const old={x:a.x,y:a.y};a.x=Math.max(40,Math.min(960,b.x+(i%2?34:-34)));a.y=b.y;this.fx('dash',old.x,old.y,a.color,'',{tx:a.x,ty:a.y,life:.3});this.fx('sword',b.x,b.y,a.color,'',{angle:i*.9,life:.35});this.hit(a,b,15);});break;
case'quiz':{const targets=this.fighters.filter(f=>f!==a&&f.health>0);for(const f of targets)this.fx('warning',f.x,f.y,a.color,'?',{radius:30,life:.65});this.schedule(a,.65,()=>{for(const f of targets){this.fx('lightning',f.x,f.y-150,a.color,'',{tx:f.x,ty:f.y,life:.5});this.hit(a,f,19);f.stun=.5;}});break;}
case'shield':a.shield=55;a.orbit=2.5;this.fx('shieldburst',a.x,a.y,a.color,'',{radius:95,life:.7});for(const f of near(a.x,a.y,95)){this.hit(a,f,22);f.stun=.7;this.knock(a,f,55);}break;
case'trap':this.zones.push({kind:'trap',x:a.x,y:a.y,owner:a.id,life:10,radius:65,color:a.color});this.fx('fork',a.x,a.y-80,a.color,'',{tx:a.x,ty:a.y,life:.4});break;
case'ghost':{const old={x:a.x,y:a.y};this.fx('portal',old.x,old.y,a.color,'',{life:.8});a.x=Math.max(45,Math.min(955,b.x-b.face*38));a.y=b.y;a.evade=1.5;this.fx('portal',a.x,a.y,a.color,'',{life:.8});this.fx('sword',b.x,b.y,a.color,'',{angle:-1});this.hit(a,b,36);break;}
case'slam':{const x=a.x,y=a.y;a.stun=.55;this.fx('warning',x,y,a.color,'CAPS',{radius:145,life:.55});this.schedule(a,.55,()=>{this.fx('keyboard',x,y,a.color,'',{radius:145,life:.8});this.fx('crack',x,y,a.color,'',{radius:145,life:1.2});this.shake=.35;for(const f of near(x,y,145)){this.hit(a,f,42);f.stun=1;this.knock(a,f,80);}});break;}
case'bomb':{for(let i=0;i<3;i++){const x=Math.max(45,Math.min(955,b.x+(i-1)*55)),y=b.y;this.fx('warning',x,y,a.color,'MAIL',{radius:48,life:.8+i*.18});this.fx('anvil',x,y,a.color,'',{life:.8+i*.18});this.schedule(a,.8+i*.18,()=>{this.fx('crack',x,y,a.color,'',{radius:55});this.burst(x,y,a.color);this.shake=.15;for(const f of near(x,y,52))this.hit(a,f,23);});}break;}
case'heal':a.health=Math.min(a.hp,a.health+38);this.fx('heal',a.x,a.y,a.color,'',{life:1.2});this.fx('text',a.x,a.y-35,a.color,'+38');this.line(a,b,'vine',a.color);b.poison=4;b.poisonOwner=a.id;break;
case'reflect':a.reflect=2.2;this.fx('swordspin',a.x,a.y,a.color,'',{radius:75,life:2.2});for(const f of near(a.x,a.y,75)){this.hit(a,f,18);this.knock(a,f,30);}break;
case'fire':{const x=b.x,y=b.y;this.fx('warning',x,y,a.color,'SUN',{radius:85,life:.7});this.schedule(a,.7,()=>{this.zones.push({kind:'fire',x,y,owner:a.id,life:4,radius:85,color:a.color,tick:0});this.fx('eruption',x,y,a.color,'',{life:1});this.shake=.15;});break;}}
}

step(dt){if(this.done)return;dt=Math.min(.05,dt);this.time+=dt;this.shake=Math.max(0,this.shake-dt);for(const p of this.pending)p.left-=dt;const due=this.pending.filter(p=>p.left<=0);this.pending=this.pending.filter(p=>p.left>0);for(const p of due){const owner=this.fighters.find(f=>f.id===p.owner);if(owner.health>0)p.action();}for(const e of this.effects)e.life-=dt;this.effects=this.effects.filter(e=>e.life>0);for(const a of this.fighters){if(a.health<=0)continue;for(const k of ['stun','evade','reflect','pose','flash','orbit'])a[k]=Math.max(0,(a[k]||0)-dt);if(a.poison>0){a.poison-=dt;let owner=this.fighters.find(f=>f.id===a.poisonOwner);if(owner&&Math.floor(this.time*3)!==Math.floor((this.time-dt)*3))this.hit(owner,a,3);}if(a.health<=0||a.stun>0)continue;const enemies=this.fighters.filter(b=>b!==a&&b.health>0);if(!enemies.length)break;enemies.sort((b,c)=>Math.hypot(b.x-a.x,b.y-a.y)-Math.hypot(c.x-a.x,c.y-a.y));const b=enemies[0];let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;a.face=dx>=0?1:-1;a.skillLeft-=dt;a.attackLeft-=dt;if(a.skillLeft<=0){this.skill(a,b);a.skillLeft=a.cd;}if(d>a.range*.8){a.x+=dx/d*a.speed*dt;a.y+=dy/d*a.speed*dt;}else if(d<30){a.x-=dx/d*15*dt;a.y-=dy/d*15*dt;}if(d<=a.range&&a.attackLeft<=0){a.attackLeft=.85+this.rng()*.2;this.attack(a,b);}a.x=Math.max(40,Math.min(960,a.x));a.y=Math.max(65,Math.min(535,a.y));}
for(const p of this.projectiles){p.life-=dt;const b=this.fighters.find(f=>f.id===p.target),a=this.fighters.find(f=>f.id===p.owner);if(!b||b.health<=0){p.life=0;continue;}let dx=b.x-p.x,dy=b.y-15-p.y,d=Math.hypot(dx,dy);if(d<p.speed*dt+10){this.hit(a,b,p.amount);p.life=0;this.fx('spark',b.x,b.y,p.color);}else{p.x+=dx/d*p.speed*dt;p.y+=dy/d*p.speed*dt;}}this.projectiles=this.projectiles.filter(p=>p.life>0);
for(const z of this.zones){z.life-=dt;const a=this.fighters.find(f=>f.id===z.owner);const victims=this.fighters.filter(f=>f.id!==z.owner&&f.health>0&&Math.hypot(f.x-z.x,f.y-z.y)<z.radius);if(z.kind==='trap'&&victims.length){for(const b of victims)this.hit(a,b,34);z.life=0;this.fx('crack',z.x,z.y,z.color,'',{radius:80});this.burst(z.x,z.y,z.color,20);this.shake=.2;}if(z.kind==='fire'){z.tick-=dt;if(z.tick<=0){for(const b of victims)this.hit(a,b,7);z.tick=.5;}}}this.zones=this.zones.filter(z=>z.life>0);const alive=this.fighters.filter(f=>f.health>0);if(alive.length<=1){this.done=true;this.winner=alive[0]||null;this.log(this.winner?this.winner.name+' wins the brawl!':'Double knockout. No survivors.','#befb58');}}
}
root.Brawl={roster,Battle};if(typeof module!=='undefined')module.exports=root.Brawl;
})(typeof window!=='undefined'?window:globalThis);
